name: Update Localisation Mod

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  update-mod:
    name: Update Mod
    runs-on: windows-latest

    steps:
      - name: Checkout Peacock
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          token: ${{ secrets.PEACOCKBOT_TOKEN }}
          path: "./Peacock"

      - name: Checkout Peacock Strings
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PEACOCKBOT_TOKEN }}
          repository: thepeacockproject/peacock-strings
          path: "./PeacockStrings"

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: "./Peacock/.nvmrc"
          cache: "yarn"
          cache-dependency-path: "./Peacock/yarn.lock"

      - name: Install Packages
        run: |
          cd Peacock
          yarn install --immutable

      - name: Download RPKG-CLI
        id: rpkgcli
        uses: robinraju/release-downloader@v1.12
        with:
          repository: "glacier-modding/RPKG-Tool"
          latest: true
          fileName: "rpkg_*-cli.zip"
          out-file-path: "Peacock/resources"

      - name: Download HMLanguageTools
        id: hmlt
        uses: robinraju/release-downloader@v1.12
        with:
          repository: "AnthonyFuller/TonyTools"
          latest: true
          fileName: "TonyTools.zip"
          out-file-path: "Peacock/resources"

      - name: Unzip dependencies
        run: |
          cd Peacock/resources
          7z x ${{ fromJson(steps.rpkgcli.outputs.downloaded_files)[0] }}
          7z x ${{ fromJson(steps.hmlt.outputs.downloaded_files)[0] }}

      - name: Rebuild Locale Packages
        run: |
          cd Peacock
          yarn rebuild-locale

      - name: Copy peacockstrings.locr.json
        run: |
          copy ./Peacock/resources/peacockstrings.locr.json ./PeacockStrings/content/chunk0/peacockstrings.locr.json

      - name: Push updated Peacock LOCR
        uses: EndBug/add-and-commit@v9
        with:
          cwd: "./PeacockStrings"
          add: content/chunk0/peacockstrings.locr.json
          author_name: PeacockBot
          author_email: admin@thepeacockproject.org
          message: "enhancement: update strings"
