name: Localisation

on:
  push:
    branches: ["master"]
    paths: ["resources/locale.json", ".github/workflows/locale.yml"]
  workflow_dispatch:

jobs:
  rebuild-locale:
    name: Rebuild Localisation
    runs-on: windows-latest

    steps:
      - name: Checkout Peacock
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PEACOCKBOT_TOKEN }}
          path: "./Peacock"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "./Peacock/.nvmrc"
          cache: "yarn"
          cache-dependency-path: "./Peacock/yarn.lock"
      
      - name: Install Packages
        run: |
          cd Peacock
          yarn install --immutable

      #- name: Download ResourceLib
      #  uses: robinraju/release-downloader@v1.7
      #  with:
      #    repository: "OrfeasZ/ZHMTools"
      #    latest: true
      #    fileName: "ResourceLib-win-x64.zip"
      #    out-file-path: "Peacock/resources"

      - name: Download RPKG-CLI
        id: rpkgcli
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "glacier-modding/RPKG-Tool"
          latest: true
          fileName: "rpkg_*-cli.zip"
          out-file-path: "Peacock/resources"

      - name: Download HMLanguageTools
        id: hmlt
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "AnthonyFuller/TonyTools"
          latest: true
          fileName: "TonyTools.zip"
          out-file-path: "Peacock/resources"

      - name: Unzip dependencies
        run: |
          cd Peacock/resources
          7z x ${{ fromJson(steps.rpkgcli.outputs.downloaded_files)[0] }}
          7z x ${{ fromJson(steps.hmlt.outputs.downloaded_files)[0] }}

      - name: Rebuild Locale Packages
        run: |
          cd Peacock
          yarn rebuild-locale

      - name: Push updated RPKG files
        uses: EndBug/add-and-commit@v9
        with:
          cwd: "./Peacock"
          add: |
            resources/dynamic_resources_h2.rpkg
            resources/dynamic_resources_h3.rpkg
          author_name: PeacockBot
          author_email: admin@thepeacockproject.org
          message: "[skip ci] Update locale packages"
