name: Patcher

on:
  push:
    branches: [ "v*", "master" ]
    paths: [ "patcher/**/*" ]
  pull_request:
    branches: [ "v*", "master" ]
    paths: [ "patcher/**/*" ]

env:
  DOTNET_VERSION: 8.x

jobs:
  build:
    name: Build Patcher
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build Patcher
        run: |
          export DOTNET_NOLOGO=true
          export DOTNET_CLI_TELEMETRY_OPTOUT=true
          cd patcher
          dotnet publish HitmanPatcher/HitmanPatcher.csproj -c Release -p DebugType=none -o Publish/Windows

      - name: Upload patcher-windows
        uses: actions/upload-artifact@v5
        with:
          name: patcher-windows
          path: patcher/Publish/Windows/ILRepack
